language: python

sudo: required
dist: xenial

python:
    - "2.7"
    - "3.5"

virtualenv:
    system_site_packages: true

addons:
  apt:
    packages:
    - libboost-program-options-dev
    - libboost-filesystem-dev
    - libhdf5-dev
    - python-numpy
    - python3-numpy
    - python-scipy
    - python3-scipy
    - python-matplotlib
    - python3-matplotlib
    - python-nose
    - python3-nose
    - python-coverage
    - python3-coverage
    - python-tk
    - python3-tk

before_install:
    - cwd=$(pwd)
    - git clone -b xenial https://github.com/archman/packages.git
    - cd packages/xenial
    - sudo dpkg -i *flame*.deb
    - cd ${cwd}

script:
    - cd tests
    - make test
